config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings do
      resources :orders, only: [:new, :create]
  end
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'
  root 'listings#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"


  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/
  validates :name, :description, :price, presence: true
  validates :price, numericality: {greater_than: 0}
  validates :image, attachment_presence: true
  belongs_to :user
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  validates :address, :city, :state, presence: true
  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, stretches: 12
  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :seller]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if @listing.user != current_user
        redirect_to root_url, alert: "Sorry, this listing does not belong to you!"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @listing = Listing.find(params[:listing_id])
    @order = Order.new(:listing=>@listing)
  end


  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.seller_id = @seller.id
    @order.buyer_id = current_user.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2019</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr0only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Epsy", root_path, class: "navbar-brand" %>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Epsy</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">


    <%= csrf_meta_tags %>
  </head>
  <body>


  <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true, html: {multipart: true}) do |form| %>
  <% if listing.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path, class: "btn btn-secondary" %>

app/views/listings/index.html.erb
<!--<link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">-->

<div class="jumbotron center">
  <h1>If it's handcrafted, vintage,</br>
      custom, or unique, it's on Epsy</h1>
</div>




<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency listing.price %></p>
            <p><%= "Sold by #{listing.user.name}" %></p>


          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing, class: "btn btn-link" %>

<%= link_to 'Back', listings_path, class: "btn btn-secondary" %>

app/views/listings/seller.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th class="center">Images</th>
      <th class="center">Name</th>
      <th class="center">Description</th>
      <th class="center">Price</th>
      <th class="center">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag(listing.image.url(:thumb)) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing %></li>
            <li><%= link_to "Edit", edit_listing_path(listing) %></li>
            <li><%= link_to "Destroy", listing, method: :delete, data: {confirm: "Are you sure?"} %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag(@listing.image.url(:medium)) %><br/>
    <% if user_signed_in? && current_user == @listing.user %>
      <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link " %>
    <% end %>

      <%= link_to 'Back', listings_path, class: "btn btn-link" %>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency @listing.price %></p>
    <p><%= "Sold by #{@listing.user.name}" %></p>
    <p><%= @listing.description %></p>
    <br>
    <div class="center">
      <%= link_to "Buy now", new_listing_order_path(@listing), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/orders/_form.html.erb
<%= form_for [@listing, @order] do |form| %>
    <% if @order.errors.any? %>
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize( @order.errors.count, "error") %> prohibited this order from being saved:</h4>
          <ul>
            <% @order.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :city %>
      <%= form.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :state %>
      <%= form.text_field :state, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Complete Order", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path, class: "btn btn-primary" %>

app/views/orders/payment.html.erb
<%= form_tag payment_path do %>
  <article>
    <label class="amount">
      <span>Amount: $<%= @order.price %></span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.storage.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @order.price %>"
          data-locale="auto"></script>
<% end %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Purchases</h2>
</div>

<table class="table table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th class="center">Images</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag(order.listing.image.url(:thumb)) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(listing.price) %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y")%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Your Sales History</h2>
</div>

<table class="table table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th class="center">Images</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag(order.listing.image.url(:thumb)) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td> class="center"<%= order.buyer.name%></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary" %>
<% end %>

app/views/pages/about.html.erb
<a href="/pages/about">About</a>
<a href="/pages/contact">Contact</a>

<h1>Welcome to Epsy!</h1>
<p>This is a platform that sells and buys handmade goods.</p>

app/views/pages/contact.html.erb
<a href="/pages/about">About</a>
<a href="/pages/contact">Contact</a>


<h1>Email us about more info at chinweenie@gmail.com</h1>